variables:
  RUBY_IMAGE: "ruby:2.5.1"

.registry: &registry
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
#  - build
 - test

# "Docker build":
#   <<: *registry
#   stage: build
#   script:
#     - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

"Tests":
  stage: test
  image: $RUBY_IMAGE
  script:
    - bundle install
    - rails test

"SAST":
  stage: test
  image: $RUBY_IMAGE
  script:
    - gem install brakeman
    - brakeman

