variables:
  RUBY_IMAGE: "ruby:2.5.1"
  # define image name for ease of use
  IMAGE_NAME: $HARBOR_REGISTRY/$HARBOR_PROJECT_NAME/$CI_PROJECT_NAME

stages:
 - test
 - deploy

"Tests":
  stage: test
  image: $RUBY_IMAGE
  script:
    - bundle install
    - rails test

"SAST":
  stage: test
  image: $RUBY_IMAGE
  script:
    - gem install brakeman
    - brakeman

# Changed to use HARBOR instead of GitLab registry
.registry: &registry
  image: docker:stable
  services:
    - name: docker:dind
      command: ["--insecure-registry=harbor.secpipe.stmpy.me"]
  before_script:
    - echo "USER: $HARBOR_USER"
    - echo "PASS: `echo $HARBOR_PASSWORD | wc`"
    - echo "REGISTRY: $HARBOR_REGISTRY"
    - echo "PROJ_NAME: $HARBOR_PROJECT_NAME"
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" "$HARBOR_REGISTRY"

# run docker build, and push image to harbor registry
"Docker Build":
    <<: *registry
    stage: deploy
    script:
        - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHA" ./
        - docker push "$IMAGE_NAME:$CI_COMMIT_SHA"

